import {useState, useEffect, useRef} from 'react';
import Head from 'next/head'
import * as THREE from '../three.module.js';
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

const characters = [
	{
		name: 'Scillia',
		imgSrc: 'characters/scillia.png',
		class: 'Drop Hunter',
	},
	{
		name: 'Drake',
		imgSrc: 'characters/drake.png',
		class: 'Hacker Supreme',
	},
	{
		name: 'Hyacinth',
		imgSrc: 'characters/hyacinth.png',
		class: 'Beast Influencer',
	},
	{
		name: 'Juniper',
		imgSrc: 'characters/juniper.png',
		class: 'Academy Engineer',
	},
	{
		name: 'Anemone',
		imgSrc: 'characters/anemone.png',
		class: 'Lisk Witch',
	},
];

const colors = [
  // [
    0xcd782e,
    0xe5fec0,
  // ],
  // [
    0xc44d31,
    0xfffe83,
  // ],
  // [
    0xab2b44,
    0xfffe60,
  // ],
  // [
    0x912552,
    0xffed4c,
  // ],
  // [
    0x66217a,
    0xffa146,
  // ],
  // [
    0x532b8b,
    0xff7559,
  // ],
  // [
    0x2a3dab,
    0xff4a7d,
  // ],
  // [
    0x1755bb,
    0xf830a5,
  // ],
  // [
    0x0076c4,
    0xa93dec,
  // ],
  // [
    0x009fb4,
    0x5d67fa,
  // ],
  // [
    0x0dafad,
    0x457ffc,
  // ],
  // [
    0x49bf85,
    0x00c0fc,
  // ],
  // [
    0x69c776,
    0x00e8fc,
  // ],
  // [
    0x9bbe58,
    0x22fffe,
  // ],
  // [
    0xafad42,
    0x55fffc ,
  // ],
  // [
    0xc38b34,
    0xb5ffef,
  // ],
];
const Arrow = ({arrowPosition, arrowDown, svgData}) => {
	const ref = useRef(null);
	useEffect(() => {
	  console.log('got ref current', ref.current);
	}, [ref.current]);
	// console.log('render', arrowPosition);
	const characterWidth = typeof window !== 'undefined' ?
	  (window.innerWidth - 50*2 - (characters.length - 1)*30)/characters.length + 30
	:
	  0;
	return (
    <div
		  className={styles.arrow}
      style={{
				left: `${characterWidth * arrowPosition - 32}px`,
				transform: arrowDown ? `scale(0.8)` : null,
			}}
		  dangerouslySetInnerHTML={{__html: svgData}}
			ref={ref}
		>
		</div>
  );
};
export default function Home() {
  const state = useState();
	
	return (
    <div className={styles.page}>
      <Head>
        <title>Upstreet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			
			<div className={styles.characters}>
			  
			</div>
    </div>
  )
}
